service: realworld

provider:
  name: aws
  runtime: nodejs12.x
  # region: us-east-1
  environment:
    DYNAMODB_NAMESPACE: ${opt:stage, "dev"}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/*"

package:
  exclude:
    - test/**
    - coverage/**
    - lambda-node-logo.png
    - .nyc_output/**

plugins:
  - serverless-dynamodb-local
  - serverless-offline

functions:

  ## Users API
  createUser:
    handler: src/User.create
    memorySize: 1024
    events:
      - http:
          method: POST
          path: /api/users
          cors: true

  loginUser:
    handler: src/User.login
    memorySize: 1024
    events:
      - http:
          method: POST
          path: /api/users/login
          cors: true

  getUser:
    handler: src/User.get
    memorySize: 1024
    events:
      - http:
          method: GET
          path: /api/user
          cors: true

  updateUser:
    handler: src/User.update
    memorySize: 1024
    events:
      - http:
          method: PUT
          path: /api/user
          cors: true

  getProfile:
    handler: src/User.getProfile
    memorySize: 1024
    events:
      - http:
          method: GET
          path: /api/profiles/{username}
          cors: true

  followUser:
    handler: src/User.follow
    memorySize: 1024
    events:
      - http:
          method: POST
          path: /api/profiles/{username}/follow
          cors: true

  unfollowUser:
    handler: src/User.follow
    memorySize: 1024
    events:
      - http:
          method: DELETE
          path: /api/profiles/{username}/follow
          cors: true

  ## Articles API
  createArticle:
    handler: src/Article.create
    memorySize: 1024
    events:
      - http:
          method: POST
          path: /api/articles
          cors: true

  getArticle:
    handler: src/Article.get
    memorySize: 1024
    events:
      - http:
          method: GET
          path: /api/articles/{slug}
          cors: true

  udpateArticle:
    handler: src/Article.update
    memorySize: 1024
    events:
      - http:
          method: PUT
          path: /api/articles/{slug}
          cors: true

  deleteArticle:
    handler: src/Article.delete
    memorySize: 1024
    events:
      - http:
          method: DELETE
          path: /api/articles/{slug}
          cors: true

  favoriteArticle:
    handler: src/Article.favorite
    memorySize: 1024
    events:
      - http:
          method: POST
          path: /api/articles/{slug}/favorite
          cors: true

  unfavoriteArticle:
    handler: src/Article.favorite
    memorySize: 1024
    events:
      - http:
          method: DELETE
          path: /api/articles/{slug}/favorite
          cors: true

  listArticles:
    handler: src/Article.list
    memorySize: 1024
    events:
      - http:
          method: GET
          path: /api/articles
          cors: true

  getArticlesFeed:
    handler: src/Article.getFeed
    memorySize: 1024
    events:
      - http:
          method: GET
          path: /api/articles/feed
          cors: true

  getTags:
    handler: src/Article.getTags
    memorySize: 1024
    events:
      - http:
          method: GET
          path: /api/tags
          cors: true

  ## Comments API
  createComment:
    handler: src/Comment.create
    memorySize: 1024
    events:
      - http:
          method: POST
          path: /api/articles/{slug}/comments
          cors: true

  getComments:
    handler: src/Comment.get
    memorySize: 1024
    events:
      - http:
          method: GET
          path: /api/articles/{slug}/comments
          cors: true

  deleteComment:
    handler: src/Comment.delete
    memorySize: 1024
    events:
      - http:
          method: DELETE
          path: /api/articles/{slug}/comments/{id}
          cors: true

  ## Utils API
  ping:
    handler: src/Util.ping
    memorySize: 1024
    events:
      - http:
          method: GET
          path: /api/ping
          cors: true

  purgeData:
    handler: src/Util.purgeData
    memorySize: 1024
    events:
      - http: DELETE /api/__TESTUTILS__/purge

resources:
  Resources:

    UsersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: username
            AttributeType: S
          -
            AttributeName: email
            AttributeType: S
        KeySchema:
          -
            AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: realworld-${self:provider.environment.DYNAMODB_NAMESPACE}-users
        GlobalSecondaryIndexes:
          -
            IndexName: email
            KeySchema:
              -
                AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL

    ArticlesDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: slug
            AttributeType: S
          -
            AttributeName: dummy
            AttributeType: S
          -
            AttributeName: updatedAt
            AttributeType: N
        KeySchema:
          -
            AttributeName: slug
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: realworld-${self:provider.environment.DYNAMODB_NAMESPACE}-articles
        GlobalSecondaryIndexes:
          -
            IndexName: updatedAt
            KeySchema:
              -
                AttributeName: dummy
                KeyType: HASH
              -
                AttributeName: updatedAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

    CommentsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
          -
            AttributeName: slug
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: realworld-${self:provider.environment.DYNAMODB_NAMESPACE}-comments
        GlobalSecondaryIndexes:
          -
            IndexName: article
            KeySchema:
              -
                AttributeName: slug
                KeyType: HASH
            Projection:
              ProjectionType: ALL
